title: Seokhwan Kim
description: Web & Blockchain Developer
site_title: '@greyco1or - Seokhwan Kim'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: greyco1or
blog_url: https://blog.naver.com/starbux630
email: starbux630@naver.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/myPhoto.jpg

# Google Analytics ID
google_analytics: 